




LABEL Msg BYTE    
;----------------page1------------------
        db "                              "
        db "                              "
        db "                              "
        db "        JOIN US AT THE        "
        db "                              "
        db "                              "
        db "                              "
        db "                              "
        db "                              "
        db "                              "
        db " SOON TO BE UP WITH LOADS OF  "
        db " STUFF.    LOCATED IN VIENNA. "
        db "                              "
        db "       +43-1-IDONTKNOW        "


;----------------page2------------------
        db " DEMOS                        "
        db "  INTROS                      "
        db "   SOURCECODES                "
        db "    TOOLS                     "
        db "     SNES-CODING              "
        db "      GRAFIX                  "
        db "       MULTICHANNEL-MODS      "
        db "        TEXTFILES             "
        db "         GUS-AREA             "
        db "                              "
        db "AND EVERYTHING ELSE YOU WOULD "
        db "LIKE TO GET...                "
        db "                              "
        db "                              "


;----------------page3------------------
        db "                              "
        db " IT WILL BE A SO FAR UNKNOWN  "
        db "  EXPERIENCE OF A WONDERFUL   "
        db "        KIND TO YOU...        "
        db "                              "
        db "                              "
        db "     CAN -YOU- TAKE IT        "
        db "                              "
        db "                              "
        db " CHECK OUT BOARDS AROUND THE  "
        db "  WORLD FOR DA NUMBAZ WHEN    "
        db "   IT IS UP...                "
        db "                              "
        db " AUSTRIA JOINED THE EU. YEAH. "



;----------------page4------------------

        db "                              "
        db " SPECIAL PERSONAL HELLOS FROM "
        db " JEZ MORPH TO                 "
        db "                              "
        db "  XTENDED PLEASURE            "
        db "  SLOWHAND OF SURPRISE        "
        db "  REEBOK   OF SURPRISE        "
        db "  BORIS OTTLIEWESKI           "
        db "  WOW                         "
        db "  AYATOLLAH                   "
        db "  ALL SURPRISE MEMBERS        "
        db "  ALL DUDES OWNING A GUS      "
        db "  EVERYONE SPREADING THIS     "
        db "  .........AND YOU            "

